name: CI_CD Build and Deploy Backend

on:
  release:
    types: [published]      # runs only when Release-Please creates a version tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_EVENT_RELEASE_TAG_NAME#v}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            
      
      # Build & push versioned image
      - name: Build & Push Docker Image
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker build -t ghcr.io/kressin-labs/inventory-backend:$VERSION .
          docker push ghcr.io/kressin-labs/inventory-backend:$VERSION

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            VERSION="${GITHUB_REF#refs/tags/}"
            VERSION="${VERSION#v}"
            
            cd /opt/inventory_backend
            
            # Update version in .env
            echo "BACKEND_VERSION=$VERSION" | sudo tee .env > /dev/null
            
            # force pull correct tagged version
            docker compose pull inventory-backend
            
            # redeploy container with same version
            docker compose up -d --force-recreate --no-deps inventory-backend
            
            # delete old image version, to prevent the vps storage from filling up
            docker image prune -af --filter "until=24h"
